### ISSUE TITLE
Changing render scale makes the headset warped incorrectly

### ISSUE THREAD

**Issue by SmartCarrion** [ValveSoftware/the_lab_renderer#10]
When i use adaptive quality settings and the rendering scale changes, the image is no longer warped correctly on the headset, meaning the eyes don't match up, and only a portion of the screen is displayed.  What am I doing wrong?

Solution so far is to just turn off adaptive rendering, which leads to surprisingly more performance and a usable headset.

**Comment by SmartCarrion** [comment]
It is something with the renderViewportScale, when i don't adjust that (just set it to 1) it is fine.  This is line 815 in ValveCamera.cs.  Is anyone else having this issue?  Maybe the new Unity 5.4f3 is automatically adjusting the viewport scale and this is double setting it?

`if ( VRSettings.enabled )
        {
            VRSettings.renderScale = flRenderTargetScale;
            //VRSettings.renderViewportScale = ( m_adaptiveQualityRenderScaleArray[ nAdaptiveQualityLevel ] / flRenderTargetScale ) * flAdditionalViewportScale;
            VRSettings.renderViewportScale = 1;
            //Debug.Log( "VRSettings.renderScale " + VRSettings.renderScale + " VRSettings.renderViewportScale " + VRSettings.renderViewportScale + "\n\n" );
        }`

**Comment by SmartCarrion** [comment]
I think this is a bug with Unity's new single pass rendering system, but i haven't tested it further, i'm just not using adaptive quality anymore

**Comment by KevinComerford** [comment]
Yeah, it doesn't seem to support the single pass rendering system out of the box.

**Comment by kideternal** [comment]
The bug indeed occurs when setting VRSettings.renderViewPortScale in UpdateAdaptiveQuality(). 

I don't believe it's related to single-pass, as I'm not using that, but it's possible Unity broke something while implementing it.

Setting "renderScale" works, but not "renderViewPortScale".

I believe it's due to a conflict with an ImageEffect or possibly something else using RenderTexture.active, as I've experimented with another project and it's working just fine there.  Disabling ImageEffects might work for you, but it's giving me hundreds of "entry->m_Rect.width == width" errors.  (Besides, I need these ImageEffects!)

Doubling the renderViewPortScale on that line gets it closer to what it should be, but there's still a field-of-view issue making everything skew/pancake.

**Comment by SmartCarrion** [comment]
fixed in Unity.
